name: brilliant_sdk
description: Brilliant SDK - Flutter package for Brilliant Labs Halo and Frame devices
version: 1.0.0
homepage: https://github.com/brilliantLabsAR/brilliant_sdk
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  frame_ble:
    path: ../frame_ble
  frame_msg:
    path: ../frame_msg


dev_dependencies:
  flutter_test:
    sdk: flutter