name: layout
description: "Brilliant SDK Layout Sample"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.36.8
  logging: ^1.3.0
  # Note: We use a path dependency because the example apps & library packages are bundled together.
  # In *your* app you should use a versioned dependency from pub.dev
  simple_frame_app:
    path: ../../
  frame_msg:
    path: ../../../frame_msg  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/frame_msg/lua/battery.min.lua
    - packages/frame_msg/lua/code.min.lua
    - packages/frame_msg/lua/data.min.lua
    - packages/frame_msg/lua/imu.min.lua
    - packages/frame_msg/lua/plain_text.min.lua
    - packages/frame_msg/lua/sprite.min.lua
    - packages/frame_msg/lua/text_sprite_block.min.lua
    - packages/frame_msg/lua/image_sprite_block.min.lua
    - assets/lua/layout/base_layout.lua
    - assets/lua/layout/text_layout.lua
    - assets/lua/layout/speech_layout.lua
    - assets/lua/layout/encounter_layout.lua
    - assets/lua/view/bg_view.lua
    - assets/lua/view/image_view.lua
    - assets/lua/view/text_view.lua
    - assets/lua/view/speech_wave_view.lua
    - assets/lua/view/header_view.lua
    - assets/lua/view/speech_wave.lua
    - assets/lua/view/view.lua
    - assets/frame_app.lua
    - assets/images/
  fonts:
    - family: DogicaPixel
      fonts:
        - asset: assets/fonts/dogica/dogicapixel.ttf
          weight: 700
