name: image_gen_pollinations
description: "Generative AI images for Halo and Frame using pollinations.ai"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  image: ^4.2.0
  logging: ^1.2.0
  share_plus: ^10.1.0
  speech_to_text: ^7.0.2
  simple_frame_app:
    # Note: We use a path dependency because the example apps & library packages are bundled together.
    # In *your* app you should use a versioned dependency from pub.dev
    path: ../../
  frame_ble:
    path: ../../../frame_ble
  frame_msg:
    path: ../../../frame_msg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/frame_msg/lua/battery.min.lua
    - packages/frame_msg/lua/data.min.lua
    - packages/frame_msg/lua/sprite.min.lua
    - packages/frame_msg/lua/plain_text.min.lua
    - packages/frame_msg/lua/image_sprite_block.min.lua
    - assets/frame_app.lua
