name: camera
description: "Finds and connects to Brilliant Labs Halo or Frame, initiates a photo capture and returns the image with metadata to the host app for display in a list and sharing."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.3.0
  brilliant_ble:
    path: ../../../brilliant_ble
  brilliant_msg:
    path: ../../../brilliant_msg
  logging: ^1.2.0
  share_plus: ^10.1.0
  simple_brilliant_app:
    # Note: We use a path dependency because the example apps & library packages are bundled together.
    # In *your* app you should use a versioned dependency from pub.dev
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/brilliant_msg/lua/battery.min.lua
    - packages/brilliant_msg/lua/camera.min.lua
    - packages/brilliant_msg/lua/code.min.lua
    - packages/brilliant_msg/lua/data.min.lua
    - packages/brilliant_msg/lua/plain_text.min.lua
    - assets/frame_app.lua